sudo: false
install: true
language: android
jdk: oraclejdk8
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools

     # The BuildTools version used by your project
    - build-tools-27.0.3

    - platform-tools

     # Extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # The SDK version used to compile your project
    - android-26

  licenses:
    - '.+'
  before_install:
    - rm -rf /home/travis/.gradle/
  before_script:
    - rm -rf /home/travis/.gradle/
    - echo no | android create avd --force -n test -t android-27 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
